secretGenerator:
- name: rmt-mariadb-root-pass
  literals:
  - password=root
- name: rmt-mariadb-rmt-pass
  literals:
  - password=rmt
- name: rmt-scc-password
  literals:
  - password=
resources:
- mariadb.yaml
- rmt-pv-claim.yaml
- nginx-vhosts-configmap.yaml
- nginx.yaml
- rmt.yaml
