secretGenerator:
- name: rmt-mariadb-root-pass
  literals:
  - password=root
- name: rmt-mariadb-rmt-pass
  literals:
  - password=rmt
- name: rmt-scc-account
  literals:
  - username=
  - password=
resources:
- mariadb.yaml
- rmt-pv-claim.yaml
- nginx-vhosts-configmap.yaml
- nginx.yaml
- rmt-server.yaml
- rmt-cronjob-mirror.yaml
