apiVersion: v1
kind: Service
metadata:
  name: rmt-nginx-svc
  labels:
    app: rmt-server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: rmt-server
    tier: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rmt-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rmt-server
        tier: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: rmt-nginx-secret
      - name: rmt-ca-volume
        configMap:
          name: rmt-ca-configmap
      - name: vhosts-configmap-volume
        configMap:
          name: rmt-nginx-vhosts-configmap
      - name: rmt-persistent-storage
        persistentVolumeClaim:
          claimName: rmt-pv-claim
      initContainers:
      - name: init-rmt-server
        image: registry.opensuse.org/opensuse/busybox:latest
        command: ['sh', '-c', 'until nslookup rmt-server-svc; do echo waiting for rmt-server; sleep 2; done;']
      containers:
      - name: rmt-nginx
        image: registry.opensuse.org/opensuse/nginx:latest
        ports:
        - containerPort: 443
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/rmt/ssl
          name: secret-volume
        - mountPath: /etc/rmt/ca
          name: rmt-ca-volume
        - mountPath: /etc/nginx/vhosts.d
          name: vhosts-configmap-volume
        - mountPath: /usr/share/rmt
          name: rmt-persistent-storage
