apiVersion: v1
kind: Service
metadata:
  name: rmt-nginx-svc
  labels:
    app: rmt-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: 30080
  - name: https
    port: 443
    protocol: TCP
    nodePort: 30443
  selector:
    app: rmt-server
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rmt-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rmt-server
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: rmt-nginx-secret
      - name: vhosts-configmap-volume
        configMap:
          name: rmt-nginx-vhosts-configmap
      - name: rmt-persistent-storage
        persistentVolumeClaim:
          claimName: rmt-pv-claim
      containers:
      - name: rmt-nginx
        image: registry.opensuse.org/opensuse/nginx:latest
        # command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
        #livenessProbe:
        #  httpGet:
        #    path: /index.html
        #    port: 80
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/rmt/ssl
          name: secret-volume
        - mountPath: /etc/nginx/vhosts.d
          name: vhosts-configmap-volume
        - mountPath: /usr/share/rmt
          name: rmt-persistent-storage
