apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rmt-systems-scc-sync-cronjob
  labels:
    app: rmt-server
    tier: rmt-systems-scc-sync-cronjob
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: rmt-persistent-storage
            persistentVolumeClaim:
              claimName: rmt-pv-claim
          containers:
          - name: rmt-systems-scc-sync-cronjob
            image: registry.opensuse.org/opensuse/rmt-server:latest
            imagePullPolicy: Always
            args:
            - /usr/share/rmt/bin/rmt-cli
            - systems
            - scc-sync
            env:
            - name: MYSQL_HOST
              value: rmt-mariadb-svc
            - name: MYSQL_DATABASE
              value: rmt
            - name: MYSQL_USER
              value: rmt
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rmt-mariadb-rmt-pass
                  key: password
            volumeMounts:
            - name: rmt-persistent-storage
              mountPath: /var/lib/rmt
