apiVersion: v1
kind: Service
metadata:
  name: rmt-server-svc
  labels:
    app: rmt-server
spec:
  ports:
    - port: 4224
  selector:
    app: rmt-server
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmt-server
  labels:
    app: rmt-server
spec:
  selector:
    matchLabels:
      app: rmt-server
      tier: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rmt-server
        tier: server
    spec:
      volumes:
      - name: rmt-persistent-storage
        persistentVolumeClaim:
          claimName: rmt-pv-claim
      - name: rmt-tmp-volume
        emptyDir: {}
      containers:
      - image: registry.opensuse.org/home/kukuk/container/container/opensuse/rmt-server:latest
        name: rmt
        env:
        - name: MYSQL_HOST
          value: rmt-mariadb-svc
        - name: MYSQL_DATABASE
          value: rmt
        - name: MYSQL_USER
          value: rmt
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmt-mariadb-rmt-pass
              key: password
        - name: SCC_USERNAME
          valueFrom:
            secretKeyRef:
              name: rmt-scc-account
              key: username
        - name: SCC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmt-scc-account
              key: password
        ports:
        - containerPort: 4224
          name: suseconnect
        volumeMounts:
        - name: rmt-persistent-storage
          mountPath: /var/lib/rmt
        - name: rmt-tmp-volume
          mountPath: /usr/share/rmt/tmp
      initContainers:
      - name: init-rmt-server
        image: registry.opensuse.org/opensuse/mariadb-client:latest
        command: ['sh', '-c', 'until mysqladmin ping -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h ${MYSQL_HOST} --silent; do echo waiting for mariadb; sleep 2; done;']
        env:
        - name: MYSQL_HOST
          value: rmt-mariadb-svc
        - name: MYSQL_USER
          value: rmt
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmt-mariadb-rmt-pass
              key: password

